swagger: '2.0'
info:
  title: API d'accès aux informations de remplissage des retenues d'eau
  description: >-
    Maquette d'API d'accès aux informations de remplissage des retenues d'eau.
  version: '0.1'
  termsOfService: 'http://retenues.geoapi.fr/v1/terms/'
  contact:
    email: retenues@geoapi.fr
  license:
    name: Licence ouverte version 2.0
    url: 'https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf'
host: retenues.geoapi.fr
basePath: /v1
schemes:
  - http
  - https
paths:
  /:
    get:
      tags:
        - documentation de l'API
      summary: Retourne cette spécification de l'API en JSON
      operationId: spec
      produces:
        - application/json
      responses:
        '200':
          description: opération réussie
  /terms:
    get:
      tags:
        - documentation de l'API
      summary: Renvoie les conditions d'utilisation de l'API
      operationId: terms
      produces:
        - text/html
      responses:
        '200':
          description: opération réussie
  /retenues:
    get:
      tags:
        - retenues
      summary: Retourne la liste des retenues décrites dans le service éventuellement filtrée pour un département
      operationId: list
      produces:
        - application/json
      parameters:
        - name: departement
          in: query
          description: code INSEE du département dans lequel les retenues sont localisées
          type: string
      responses:
        '200':
          description: opération réussie
          schema:
            $ref: '#/definitions/Retenues'
        '400':
          description: paramètre fourni invalide
        '404':
          description: aucun résultat ne correspond à cette requête
  '/retenues/{numRetenue}':
    get:
      tags:
        - retenues
      summary: Retourne les mesures associées à une retenue évent. après une date donnée
      operationId: mesures
      produces:
        - application/json
      parameters:
        - name: numRetenue
          in: path
          description: Numéro de la retenue
          required: true
          type: string
        - name: date
          in: query
          description: date au format ISO 8601 après laquelle les mesures sont retournées
          type: string
      responses:
        '200':
          description: opération réussie
          schema:
            $ref: '#/definitions/ListeDeMesuresDatees'
        '400':
          description: numéro fourni invalide
        '404':
          description: aucun résultat ne correspond à cette requête
definitions:
  Retenues:
    description: Les retenues structurées comme une FeatureCollection GeoJSON
    type: object
    required:
      - type
      - features
    properties:
      type:
        type: string
        enum: [FeatureCollection]
      features:
        type: array
        items:
          type: object
          description: chaque retenue structurée comme Feature GeoJSON
          required:
            - type
            - properties
            - geometry
          properties:
            type:
              type: string
              enum: [Feature]
            properties:
              type: object
              required:
                - num
                - nom
                - nature
                - region
                - departement
                - riviere
                - date_construction
                - volume(Mm3)
                - superficie(ha)
                - altitude(mNGF)
                - usages
              properties:
                num:
                  type: integer
                  description: identifiant de la retenue unique pour la base
                nom:
                  type: string
                  description: nom donné à la retenue
                nature:
                  type: string
                  enum: [Retenue "classique"]
                region:
                  type: string
                  description: nom de la région dans laquelle la retenue est localisée
                departement:
                  type: string
                  description: code INSEE du département dans lequel la retenue est localisée
                riviere:
                  type: string
                  description: nom de la rivière sur laquelle est située la retenue
                date_construction:
                  type: string
                  format: date
                  description: date de construction en format ISO 8601
                volume(Mm3):
                  type: number
                  description: volume de la retenue en million de mètres cube
                superficie(ha):
                  type: number
                  description: superficie de la retenue en hectares
                altitude(mNGF):
                  type: number
                  description: altitude en mètres NGF
                usages:
                  description: liste des usages
                  type: array
                  items:
                    type: string
                    enum:
                      - Hydroélectricité
                      - Irrigation
                      - Alim. en eau
                      - Crues
                      - Loisirs
                      - Tourisme
                      - Soutien d'étiage
                      - Navigation
                      - Nucléaire
            geometry:
              type: object
              properties:
                type:
                  type: string
                  enum: [Point]
                coordinates:
                  type: array
                  minItems: 2
                  maxItems: 2
                  items:
                    type: number
  ListeDeMesuresDatees:
    description: liste de mesures datées associées à une retenue
    type: object
    properties:
      num:
        description: numéro de la retenue
        type: integer
      mesures:
        description: liste de mesures datées associées à la retenue
        type: array
        items:
          type: object
          required: [date, cote_bassin(m), volume(Mm3), surface(ha)]
          properties:
            date:
              description: date de la mesure
              type: string
              format: date
            cote_bassin(m):
              description: cote atteinte par le bassin en mètre NGF
              type: number
            volume(Mm3):
              description: volume retenue en millions de mètres cube
              type: number
            surface(ha):
              description: surface du bassin en hectares
              type: number
        
externalDocs:
  description: Documentation de l'API
  url: https://github.com/benoitdavidfr/retenues
